'use strict';

const path = require('path');
const dotenv = require('dotenv');

// Env files are loaded highest-priority first — dotenv never overwrites a value
// that is already set, so the first file to define a key wins:
//
//   1. real environment variables (systemd / pm2 / docker)
//   2. .env.local  — secrets. Gitignored, created once per machine, and never
//                    regenerated by CI, so a deploy can't wipe it.
//   3. .env        — non-secret config. Safe for CI to recreate from
//                    .env.example on every deploy.
//
// Everything still works with a single fully-filled .env; .env.local is only
// needed when CI owns .env and the repo is public (secrets can't be committed).
const backendRoot = path.resolve(__dirname, '..', '..');
for (const file of ['.env.local', '.env']) {
  dotenv.config({ path: path.join(backendRoot, file) });
}

function parseOrigins(raw) {
  if (!raw) return ['http://localhost:5173'];
  return raw
    .split(',')
    .map((o) => o.trim())
    .filter(Boolean);
}

const NODE_ENV = process.env.NODE_ENV || 'development';

const JWT_SECRET =
  process.env.JWT_SECRET || (NODE_ENV === 'production' ? '' : 'dev-only-change-me');

if (NODE_ENV === 'production' && (!JWT_SECRET || JWT_SECRET.length < 16)) {
  // Fail fast in production rather than signing tokens with a weak/empty secret.
  throw new Error('JWT_SECRET must be set to a strong value in production.');
}

const config = {
  env: NODE_ENV,
  isProd: NODE_ENV === 'production',
  port: Number(process.env.PORT) || 4000,
  // Interface to bind. Left UNSET by default, which keeps Node's behaviour of
  // listening on every interface — changing that on a live server could cut
  // nginx off from the API, so it stays opt-in.
  //
  // Recommended on a VPS where nginx runs on the same machine:
  //   HOST=127.0.0.1
  // That makes the API reachable only through the proxy, so nobody can hit
  // http://<VPS_IP>:4000 directly and bypass Cloudflare + nginx.
  // Keep it unset (or 0.0.0.0) if the API runs in a container or on a
  // different host than the proxy.
  host: process.env.HOST || null,
  corsOrigins: parseOrigins(process.env.CORS_ORIGIN),
  jwt: {
    secret: JWT_SECRET,
    expiresIn: process.env.JWT_EXPIRES_IN || '7d',
  },
  bcryptRounds: Number(process.env.BCRYPT_ROUNDS) || 10,
  admin: {
    username: process.env.ADMIN_USERNAME || 'admin',
    password: process.env.ADMIN_PASSWORD || (NODE_ENV === 'production' ? '' : 'admin123'),
  },
};

if (config.isProd && !config.admin.password) {
  // Never allow a blank/default admin password in production.
  throw new Error('ADMIN_PASSWORD must be set to a strong value in production.');
}

module.exports = config;
